### ISSUE TITLE
The bit 2 of the guest interruptibility state VMCS field (blocking by SMI) is set incorrectly 

### ISSUE THREAD

**Issue by tandasat** [stlintel/Bochs#10]
The blocking by SMI bit of the guest interruptibility state VMCS is set unconditionally when the SMI is blocked. This is incorrect as the Intel SDM states that the bit is set to 0 unless the VM-exit ends to SMM.
```
27.3.4 Saving Non-Register State
...
- VM exits that end outside system-management mode (SMM) save bit 2 (blocking by SMI) as 0 regardless
of the state of such blocking before the VM exit.
```

This causes the (incorrect) invalid guest state VM-exit during VM-entry after handling a VM-exit following INIT VM-exit (typically SIPI VM-exit), as a VMM would put the guest into wait-for-SIPI state to emulate INIT, which masks SMI. 
```c
void BX_CPU_C::enter_sleep_state(unsigned state)
{
// ...(this runs as a result of INIT handling)
  case BX_ACTIVITY_STATE_WAIT_FOR_SIPI:
    mask_event(BX_EVENT_INIT | BX_EVENT_SMI | BX_EVENT_NMI); 
```
```c
void BX_CPU_C::VMexitSaveGuestState(void)
{
//...(this runs at the next VM-exit after INIT handling)
  if (is_masked_event(BX_EVENT_SMI))
    interruptibility_state |= BX_VMX_INTERRUPTS_BLOCKED_SMI_BLOCKED;
```
```c
Bit32u BX_CPU_C::VMenterLoadCheckGuestState(Bit64u *qualification)
{
//..(this runs at the VM-entry after handling of the VM-exit following INIT VM-exit)
  if (guest.interruptibility_state & BX_VMX_INTERRUPTS_BLOCKED_SMI_BLOCKED) {
    if (! BX_CPU_THIS_PTR in_smm) {
      BX_ERROR(("VMENTER FAIL: VMCS SMI blocked when not in SMM mode"));
      return VMX_VMEXIT_VMENTRY_FAILURE_GUEST_STATE;
    }
  }
```
Such invalid guest state VM-exit does not happen on real machines.

A fix would be to check whether the processor is transitioning to SMM as a result of VM-exit. I modified code something like this locally but I doubt this is correct. `BX_CPU_THIS_PTR in_smm` may still be describing a context of non-root operation, and I am not entirely clear how the check should look like.
```c
void BX_CPU_C::VMexitSaveGuestState(void)
{
//...
  // VM exits that end outside system-management mode (SMM) save bit 2 (blocking by SMI)
  // as 0 regardless of the state of such blocking before the VM exit.
  if (BX_CPU_THIS_PTR in_smm && is_masked_event(BX_EVENT_SMI))
    interruptibility_state |= BX_VMX_INTERRUPTS_BLOCKED_SMI_BLOCKED;
```

**Comment by stlintel** [comment]
Do you have a real test case for this scenario ?
This was sort of shortcut from my side I did in purpose because I never saw such scenarios (cross between VMX and SMM) and didn't want to guess.

**Comment by tandasat** [comment]
I have a setup for the scenarios I described with both baremetal and Bochs. If you want me to try something out, I can do. If you want to reproduce the described scenario with Bochs on your end, I can write up setup steps here for you.

I do not have the cases for scenarios crossing (exiting to SMM & root-operation IIUC).

**Comment by stlintel** [comment]
You could submit PR without asking. It will be reviewed and of found good - merged in.
