### ISSUE TITLE
INIT signal remains pending even after delivery of VM-exit(INIT)

### ISSUE THREAD

**Issue by tandasat** [stlintel/Bochs#11]
When the destination processor of the INIT signal is in VMX non-root operation, the signal is translated into the corresponding VM-exit. In this case, Bochs keeps the INIT signal pending, and thus, when the destination processor handles VM-exit(INIT),  followed by VM-exit(SIPI), and INIT is unmasked (below), INIT is signaled again. 
```c
void BX_CPU_C::deliver_SIPI(unsigned vector)
{
//...
    unmask_event(BX_EVENT_INIT | BX_EVENT_SMI | BX_EVENT_NMI);
```

This is incorrect as the INIT was already processed as VM-exit. This causes failure of wakening up APs as they are stuck at the wait-for-SIPI state. This issue does not happen on a real machine I have tested in the past.

What I believe to be a fix is to clear the pending INIT when it is delivered as a VM-exit, as it is done for other events like `BX_EVENT_NMI`. 
```c
bool BX_CPU_C::handleAsyncEvent(void)
{
// ...
  if (is_unmasked_event_pending(BX_EVENT_INIT) && SVM_GIF) {
    clear_event(BX_EVENT_INIT);                                         // << this
#if BX_SUPPORT_SVM
    if (BX_CPU_THIS_PTR in_svm_guest) {
      if (SVM_INTERCEPT(SVM_INTERCEPT0_INIT)) Svm_Vmexit(SVM_VMEXIT_INIT);
    }
#endif
#if BX_SUPPORT_VMX
    if (BX_CPU_THIS_PTR in_vmx_guest) {
      VMexit(VMX_VMEXIT_INIT, 0);
    }
#endif
    // reset will clear pending INIT
    reset(BX_RESET_SOFTWARE);
```    

I am less certain but the same issue appears to exist for the SVM emulation as well. 

If the above change looks alright, I am happy to create a PR.

**Comment by stlintel** [comment]
Looks right, you may create PR.
Also I hope you have a way to test it ('failure of wakening up APs as they are stuck at the wait-for-SIPI state' is resolved)

**Comment by tandasat** [comment]
Cool, I am going to look into detailing steps to reproduce the issue here or in the PR to show the result of testing/changes, and create a PR.
