### ISSUE TITLE
Common/shared codebase for device emulations 

### ISSUE THREAD

**Issue by ohault** [stlintel/Bochs#28]
Currently, there are so many projects with an implementation of device emulations, like audio, video, network cards, ...

Bochs, QEMU, 86Box, PCem, ....

Wouldn't it be interesting to design a software architecture that would allow a shared implementation of emulated devices ?

At runtime, these software devices could even eventually in the longer term vision, provide a way to be run remotely (disaggregation)

**Comment by stlintel** [comment]
Nice to say, not really doable.
It is the same as talking about single emulator for all.
Actually it is exists already - Qemu.
Industry put money there and Bochs left with 2 active developers.

**Comment by ohault** [comment]
@stlintel It's not the model I was trying to describe. Each emulator has there own benefits and specializations and it should stay like this.

I guess what is currently missing is like a software standard for virtual/emulated devices that all emulators could implement to avoid implementing and maintaining each one proprietary device emulation codes for some devices. 

I can think to something similar to a driver/module interface with a kernel.

This will also provide a way for all Hypervisors, Emulation software, ... to have a common way of defining a "Machine" (configured set of hardware device interconnected) and hence reduce the duplication effort in the so many similar UI tools in this space. 

Current work in progress with https://www.opencompute.org/ and https://www.dmtf.org/standards/redfish could help.

**Comment by stlintel** [comment]
We suggested to have such standard back ago.
And QEMU raised this question in their developer forum.
Guess what was the answer.
Bochs is welcome to support what we have, we are against anything else.
And they are industry standard today.

**Comment by stlintel** [comment]
Just will leave it here
https://lists.gnu.org/archive/html/qemu-devel/2006-04/msg00124.html
