### ISSUE TITLE
Any plans to port Bochs onto Xamarin Forms / UWP or UNO Platform?

### ISSUE THREAD

**Issue by mediaexplorer74** [stlintel/Bochs#4]
Hi, Stanislav and your partners!

Nice idea to re-form Bochs onto the multiplatform app. :)

Please give more tech. details about your great project.

Some years ago I tried to walk this cold way... But my mission failed :( Tooo hard to port Bochs onto UWP C++

**Comment by stlintel** [comment]
What is UWP C++ ?
What kind of errors you had ?

**Comment by mediaexplorer74** [comment]
> What is UWP C++ ? What kind of errors you had ?

Oh... I used bad naming. I mean C++/WinRT:
https://docs.microsoft.com/en-US/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt
My goal was to "port" Bochs on Lumia 950 "windowsphone". Os is Win10Mobile that supports some old UWP apps.

> What kind of errors you had ?
About errors:

ohhhh.... there are 100500 bugs :) I am very bad C++ developer. So, I has no resources to create proper achitecture.... 
Hardest "error" (uncomleted task) was to apply SDL2 for Graphic Subsystem . There are the tons of work when You started porting Bochs

**Comment by stlintel** [comment]
Your fork looks really ancient. 
I am not even sure I know how to find changes you have done ...
Well, this port will definitely not be our priority, assuming you manage to complete it - we could look to the code.

**Comment by mediaexplorer74** [comment]
Ok. Thank You very much for answer. Good luck at all your Bochs goals

Best,
[m][e]
